apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.app.name }}