app:
  name: nginx-infra-app
  namespace: default
  env:
    - name: REDIS_URL
      value: "redis://redis-host:6379"

image: nginx:latest

service:
  replicas: 1
  port: 80
  containerPort: 80

ingress:
  host: health.printrevo.com
