name: Terraform Deploy

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 40
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET: "printrevo-terraform-state"
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup AWS Profile
        run: |
          mkdir -p ~/.aws
          echo "[printrevo-terraform]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "region = $AWS_REGION" >> ~/.aws/config

      # - name: Ensure S3 bucket for Terraform state exists
      #   run: |
      #       BUCKET_NAME="printrevo-terraform-state"
      #       REGION="eu-central-1"
      #       if ! aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
      #         if [ "$REGION" == "us-east-1" ]; then
      #           aws s3api create-bucket --bucket "$BUCKET_NAME"
      #         else
      #           aws s3api create-bucket --bucket "$BUCKET_NAME" --region "$REGION" --create-bucket-configuration LocationConstraint="$REGION"
      #         fi
      #         echo "S3 bucket $BUCKET_NAME created."
      #       else
      #         echo "S3 bucket $BUCKET_NAME already exists."
      #       fi

     
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Initialize Terraform Backend (S3)
        run: TF_LOG=DEBUG terraform init

      - name: Retrieve environment variables from AWS Parameter Store
        id: ssm
        run: |
          DB_PASSWORD=$(aws ssm get-parameter --name "rds_password" --with-decryption --query "Parameter.Value" --output text)
          echo "DB_PASSWORD=$DB_PASSWORD" >> $GITHUB_ENV
          echo "::set-output name=db_password::$DB_PASSWORD"

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      # - name: Define EKSInstanceSchedule if not exists
      #   run: |
      #     SCHEDULE_NAME="EKSInstanceSchedule"
      #     SCHEDULE=$(aws scheduler list-schedules --query "Schedules[?Name=='$SCHEDULE_NAME'].Name" --output text)
      #     if [ -z "$SCHEDULE" ]; then
      #       aws scheduler create-schedule --name "$SCHEDULE_NAME" --schedule-expression "cron(0 12-15,21-2 * * ? *)" --target '{"Arn":"arn:aws:events:region:746669216623:rule/EKSInstanceSchedule","RoleArn":"arn:aws:iam::746669216623:role/EKSInstanceScheduleRole"}' --flexible-time-window '{"Mode":"OFF"}'
      #       echo "Schedule $SCHEDULE_NAME created."
      #     else
      #       echo "Schedule $SCHEDULE_NAME already exists."
      #     fi

      - name: Get AWS Resources List 
        run: aws resourcegroupstaggingapi get-resources --tag-filters Key=Environment,Values=dev --output json | jq -r '.ResourceTagMappingList[].ResourceARN'

      - name: Get Terraform States
        run: terraform state list

      - name: Set execute permission for the import script
        run: chmod +x ./bin/terraform-import.sh

      - name: Import Modules Services by Environment Tag
        run: ./bin/terraform-import.sh dev || echo "Import script failed but continuing..."

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Terraform Plan
        run: terraform plan -out=tfplan -var aws_profile=printrevo-terraform -var github_token='${{ secrets.GH_PAT }}' -var aws_region='${{ secrets.AWS_REGION }}' -var aws_access_key_id='${{ secrets.AWS_ACCESS_KEY_ID }}' -var aws_access_secret_key='${{ secrets.AWS_SECRET_ACCESS_KEY }}' -var rds_password='${{ steps.ssm.outputs.db_password }}'

      - name: Set execute permission for the apply script
        run: chmod +x ./bin/terraform-apply.sh

      - name: Run Terraform Apply
        run: ./bin/terraform-apply.sh
       
      - name: Configure kubectl for EKS
        run: |
            aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name printrevo-dev-eks
            kubectl get nodes

      - name: Helm Install
        run: helm install printrevo-dev ./helm
